// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_tile2048 = new UnifiedAchievement("Tile2048",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQBw"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQBw"
#else
            "Tile2048"
#endif
            );

        public static UnifiedAchievement Tile2048
        {
            get { return s_tile2048; }
        }

        private static readonly UnifiedAchievement s_tile4096 = new UnifiedAchievement("Tile4096",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQCA"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQCA"
#else
            "Tile4096"
#endif
            );

        public static UnifiedAchievement Tile4096
        {
            get { return s_tile4096; }
        }

        private static readonly UnifiedAchievement s_tile8192 = new UnifiedAchievement("Tile8192",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQCQ"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQCQ"
#else
            "Tile8192"
#endif
            );

        public static UnifiedAchievement Tile8192
        {
            get { return s_tile8192; }
        }

        private static readonly UnifiedAchievement s_tile16384 = new UnifiedAchievement("Tile16384",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQCg"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQCg"
#else
            "Tile16384"
#endif
            );

        public static UnifiedAchievement Tile16384
        {
            get { return s_tile16384; }
        }

        private static readonly UnifiedAchievement s_tile32768 = new UnifiedAchievement("Tile32768",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQCw"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQCw"
#else
            "Tile32768"
#endif
            );

        public static UnifiedAchievement Tile32768
        {
            get { return s_tile32768; }
        }

        private static readonly UnifiedAchievement s_tile65536 = new UnifiedAchievement("Tile65536",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQDA"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQDA"
#else
            "Tile65536"
#endif
            );

        public static UnifiedAchievement Tile65536
        {
            get { return s_tile65536; }
        }

        private static readonly UnifiedAchievement s_tile131072 = new UnifiedAchievement("Tile131072",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQDQ"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQDQ"
#else
            "Tile131072"
#endif
            );

        public static UnifiedAchievement Tile131072
        {
            get { return s_tile131072; }
        }

        private static readonly UnifiedAchievement s_points5000 = new UnifiedAchievement("Points5000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQDg"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQDg"
#else
            "Points5000"
#endif
            );

        public static UnifiedAchievement Points5000
        {
            get { return s_points5000; }
        }

        private static readonly UnifiedAchievement s_points10000 = new UnifiedAchievement("Points10000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQDw"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQDw"
#else
            "Points10000"
#endif
            );

        public static UnifiedAchievement Points10000
        {
            get { return s_points10000; }
        }

        private static readonly UnifiedAchievement s_points25000 = new UnifiedAchievement("Points25000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQEA"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQEA"
#else
            "Points25000"
#endif
            );

        public static UnifiedAchievement Points25000
        {
            get { return s_points25000; }
        }

        private static readonly UnifiedAchievement s_points50000 = new UnifiedAchievement("Points50000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQEQ"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQEQ"
#else
            "Points50000"
#endif
            );

        public static UnifiedAchievement Points50000
        {
            get { return s_points50000; }
        }

        private static readonly UnifiedAchievement s_points100000 = new UnifiedAchievement("Points100000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQEg"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQEg"
#else
            "Points100000"
#endif
            );

        public static UnifiedAchievement Points100000
        {
            get { return s_points100000; }
        }

        private static readonly UnifiedAchievement s_points200000 = new UnifiedAchievement("Points200000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQEw"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQEw"
#else
            "Points200000"
#endif
            );

        public static UnifiedAchievement Points200000
        {
            get { return s_points200000; }
        }

        private static readonly UnifiedAchievement s_points300000 = new UnifiedAchievement("Points300000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQFA"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQFA"
#else
            "Points300000"
#endif
            );

        public static UnifiedAchievement Points300000
        {
            get { return s_points300000; }
        }

        private static readonly UnifiedAchievement s_points400000 = new UnifiedAchievement("Points400000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQFQ"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQFQ"
#else
            "Points400000"
#endif
            );

        public static UnifiedAchievement Points400000
        {
            get { return s_points400000; }
        }

        private static readonly UnifiedAchievement s_points600000 = new UnifiedAchievement("Points600000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQFg"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQFg"
#else
            "Points600000"
#endif
            );

        public static UnifiedAchievement Points600000
        {
            get { return s_points600000; }
        }

        private static readonly UnifiedAchievement s_points800000 = new UnifiedAchievement("Points800000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQFw"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQFw"
#else
            "Points800000"
#endif
            );

        public static UnifiedAchievement Points800000
        {
            get { return s_points800000; }
        }

        private static readonly UnifiedAchievement s_points1000000 = new UnifiedAchievement("Points1000000",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "CgkImujK958PEAIQGA"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkImujK958PEAIQGA"
#else
            "Points1000000"
#endif
            );

        public static UnifiedAchievement Points1000000
        {
            get { return s_points1000000; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_tile2048,
            s_tile4096,
            s_tile8192,
            s_tile16384,
            s_tile32768,
            s_tile65536,
            s_tile131072,
            s_points5000,
            s_points10000,
            s_points25000,
            s_points50000,
            s_points100000,
            s_points200000,
            s_points300000,
            s_points400000,
            s_points600000,
            s_points800000,
            s_points1000000,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "Tile2048", s_tile2048 },
            { "Tile4096", s_tile4096 },
            { "Tile8192", s_tile8192 },
            { "Tile16384", s_tile16384 },
            { "Tile32768", s_tile32768 },
            { "Tile65536", s_tile65536 },
            { "Tile131072", s_tile131072 },
            { "Points5000", s_points5000 },
            { "Points10000", s_points10000 },
            { "Points25000", s_points25000 },
            { "Points50000", s_points50000 },
            { "Points100000", s_points100000 },
            { "Points200000", s_points200000 },
            { "Points300000", s_points300000 },
            { "Points400000", s_points400000 },
            { "Points600000", s_points600000 },
            { "Points800000", s_points800000 },
            { "Points1000000", s_points1000000 }
        };
    }
}
